services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - JUPYTER_URL=http://jupyter:8888
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-devtoken}
      - HCLOUD_TOKEN=${HCLOUD_TOKEN:-default_fallback_token}
      - QDRANT_URL=${QDRANT_URL:-http://localhost:6333}
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      - PYTHONUNBUFFERED=1
      - DEV_MODE=true
    volumes:
      - .:/app:cached
      - ./data:/app/data
      - ./mpcs:/app/mpcs
      - ./data/.ssh:/root/.ssh:ro
      - shared_data:/app/shared
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - jupyter

  jupyter:
    image: jupyter/datascience-notebook:x86_64-ubuntu-22.04
    container_name: jupyter_notebook
    user: root
    restart: unless-stopped
    environment:
      - NB_USER=root
      - NB_UID=0
      - NB_GID=0
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-devtoken}
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    volumes:
      - ./notebooks:/home/jupyter/work
      - shared_data:/home/jupyter/shared
      - ./mpcs:/home/jupyter/app/mpcs
      - ./data:/home/jupyter/app/data
      - .:/home/jupyter/app:cached
    ports:
      - "8888:8888"
    networks:
      - app_network

volumes:
  shared_data:

networks:
  app_network:
    driver: bridge