---
name: App deploy
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create hosts file
        run: |
          echo "[all]" > hosts
          echo "142.132.227.145" >> hosts

      - name: Run playbook with Jupyter token
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbooks/deploy.yaml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            142.132.227.145 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGfYp8ib7Sae4g4Ndpnl5B8kT7aC3qRdoJ7NqycfkSc
          options: |
            --inventory hosts
            --user=root
            --extra-vars "jupyter_token=${{ secrets.SECRET_JUPYTER_TOKEN }} ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }} HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}"